name: build java_zulu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *"
  push:
    branches:
      - main
    paths:
      - java-zulu/**
concurrency:
  group: java-zulu-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "pterodactyl-images:java_${{ matrix.tag }}_zulu"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 7
          - 8
          - 11
          - 17
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./java-zulu
          file: ./java-zulu/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/Maks1116/pterodactyl-images:java_${{ matrix.tag }}_zulu
